### ISSUE TITLE
Possible null pointer dereference: pcAddr++

### ISSUE THREAD

**Issue by johnsonjh** [johnsonjh/duma#118]
#### Currently on:
+ **Commit**:  cdad2bd03fc52e22da120b18f2f5753090375299
+ **File**:    [src/duma.c](https://github.com/johnsonjh/duma/blob/cdad2bd03fc52e22da120b18f2f5753090375299/src/duma.c)
+ **LineNum**: [686](https://github.com/johnsonjh/duma/blob/cdad2bd03fc52e22da120b18f2f5753090375299/src/duma.c#L686)

**Comment by hayguen** [comment]
this definitely is intentional to provoke a core dump - as documented a few lines above this instruction

**Comment by johnsonjh** [comment]
Haven't looked at these Codacy issues just yet, just enabled the creation of issues automatically. 

Seem there isn't a way to annotate the source from comments for Codacy for all linters but I took care of it via the dashboard.
