### ISSUE TITLE
Public signing key

### ISSUE THREAD

**Issue by PeterBBBBB** [johnsonjh/duma#169]
I'm unable to retrieve the signing key F1AFCF1143EA6309
Does it need to be uploaded to key servers?

Cheers,
Peter

gpg --keyserver keys.openpgp.org --recv-key **F1AFCF1143EA6309**
gpg: **keyserver receive failed: No data**

**Comment by johnsonjh** [comment]
All keys should now be listed on all current key servers - thanks for the report.
