### ISSUE TITLE
testalloc0.cpp crashes

### ISSUE THREAD

**Issue by PeterBBBBB** [johnsonjh/duma#189]
Experimental test testalloc0.cpp crashes around line 80

` if ( argc >= 1 )
	test = atoi( argv[1] );
`

args are indexed from zero, so I think code should be

` if ( argc >= 2 )
	test = atoi( argv[1] );
`

**Comment by johnsonjh** [comment]
Thanks, I'll look at this today.  I hope to get a new release out soon.
