### ISSUE TITLE
Use CMake for building instead of simple make

### ISSUE THREAD

**Issue by johnsonjh** [johnsonjh/duma#2]
[ @suamor - Issue https://github.com/hayguen/duma_sf/issues/1 replicated. ]

Use cmake instead of simple make for project management.

**Advantages:**
- Can be opened in QtCreator
- Easier handling of dependencies
- Less overhead for installation
- Eases support for multiple platforms
- Handling 32bit and 64bit compilations independent of CMakeFile 
- Much easier to build outside src folder
- Less maintenance
- Compiler can be changed without needing to change makefile

**Disadvantages (apart from porting work)**
- Syntax of cmake may need some time to get used to
- Extra Tool dependency for building
- Extra project preparation step (cmake call) before actual build (however there also is cmake --build)
- Build files are hidden in CMakeFiles folder
- Different variable used for defining compiler and options (CMAKE_...)

**Comment by johnsonjh** [comment]
@suamor

Unfortunately, I'm really unfamiliar with *CMake*, mostly because every time I've tried to use it, I always seems to fail miserably. This likely is more a problem with me than *CMake*, but I'd just not be comfortable porting to it and maintaining it. Also, I've really never used *QtCreator*. (My experience is with *Vim-ALE*, *Eclipse*, and *VSCode*.)

I do happen to be well versed in *autotools*/*autoconf*/*automake*, which, done right, would allow for relatively easy builds outside of the source tree, compiler selection via variables, cross-compilation, etc. - I'll acknowledge that nobody seems to like it these days, and the `configure` scripts it generates are single-threaded and slow. Also, it's a big pain to initially get working. 

Another alternative might be making better use of the GNU Make extensions, which would also allow checking most of your boxes, but less and less systems seem to ship GNU Make these days (like OS X) due to the GPLv3 licensing, and getting a long-term maintainable result requires taking extra care.

Perhaps we might have luck using a simpler alternative?

While I've never actually used it for any of own projects, [Meson](https://mesonbuild.com/) (with Ninja) has always seemed to work very well everywhere I've encountered it, and it's never given me any negative experiences. It does add a dependency on Python, however. Meson *could* be implemented in any language, but the reference Python version is the only one that's well-supported. I've also used [mkconfig](https://gentoo.com/di/mkconfig.html), but will acknowledge it's a bit obscure, and it doesn't have built-in support for cross-compilation.

I'm actually not opposed to supporting multiple build systems as long they get proper testing - I'd surely not reject a PR adding CMake support, for example.

**Comment by hayguen** [comment]
have a look at https://github.com/hayguen/duma/tree/cmake

**Comment by johnsonjh** [comment]
Looks good, I'll give it a try on various systems today.

**Comment by johnsonjh** [comment]
No so fast, bots!

Leaving open for now until more testing can be completed.

**Comment by johnsonjh** [comment]
Initial tests seem good- will open new items for specific problems
