### ISSUE TITLE
Reproducible build issue (use of 'date')

### ISSUE THREAD

**Issue by PeterBBBBB** [johnsonjh/duma#206]
Use of `'date'` in `make_git_source_version.sh` makes the build unreproducible. Can be fixed (on Linux anyway) by changing to `'__DATE__'`

**Comment by johnsonjh** [comment]
@PeterBBBBB 

I believe that is used only for the herald:

`DUMA (shared) 2.5.24.BETA.1+-g7340050 2022-06-16 (compiled 2022-09-04)`

If you require a fully reproducible build (and cannot or don't want to use something like libfaketime), it would probably be better to just remove the compilation date from the herald completely.  

Would making that optional be a good solution?

**Comment by PeterBBBBB** [comment]
The problem is that without some fix, it fails Debian's reprotest tool,
so we have a patch to change `date` to `__DATE__`
I guess that making the date in the herald optional should also fix it.

**Comment by johnsonjh** [comment]
@PeterBBBBB 

If you set REPRODUCIBLE=1 in your package build environment (assuming this is a completely clean build environment for package building purposes) does this appease things?

Herald would be like: `DUMA (static) 2.5.24.BETA.1+-g76d4987 2023-11-29`.
