### ISSUE TITLE
Typo on library name (libduma.so) in man page. Wrong number of zeros.

### ISSUE THREAD

**Issue by PeterBBBBB** [johnsonjh/duma#222]
The man page includes
`the statement export LD_PRELOAD=libduma.so.0.0 will cause DUMA to be loaded`

however, on both Arch & Debian we have
libduma.so
libduma.so.0
libduma.so.0.0.0
but NOT any libduma.so.0.0 !

Suggest removing the trailing .0.0 in the man page so we have 
`the statement export LD_PRELOAD=libduma.so will cause DUMA to be loaded`
otherwise, DUMA will not be loaded, as the file libduma.so.0.0 does not exist.

**Comment by johnsonjh** [comment]
Sure, I'll make this change in master.  Probably wouldn't have tripped too many up, but still a tad bit embarassing. :)

As an aside, I should look at making a new release soon - while there isn't a lot of action here in the repo, I'm using DUMA in CI/CD pipelines of various projects so it gets used literally every day by me (and others), so if anything breaks in it, it'll get fixed quickly!  

I'll want to look at #192 and #193 first though.
