### ISSUE TITLE
Fixing support for macOS (OS X)

### ISSUE THREAD

**Issue by johnsonjh** [johnsonjh/duma#3]
[ @suamor - Issue hayguen/duma/issues/2 replicated. ]

Duma does not build for gcc-6 and newer.
clang version 6 works (did not test later clang, but they may fail as well).

**Comment by suamor** [comment]
Hi, I'm very busy with lots of things. I have introduced duma as one possibility to actively check for possible stability issues.
I'm not in the core team that decides and tests possible tools, but I know that these tools need to run at least on Linux desktop, but preferably also in Embedded environment (Yocto, maybe more in the future).

Newer compilers have a lot more memory checks on compile time already (with corresponding warnings). Also there are clang-tidy and friends for additional code analysis. In this regard it is important that duma also works fine in a modern environment (gcc-10, llvm-11, clang version with C++ 20 support and later).

**Comment by johnsonjh** [comment]
I'll look into getting a CI/CD workflow setup with Travis CI or Circle CI or GitLab CI (project is also pushed to https://gitlab.gridfinity.com/jeff/duma).

**Comment by johnsonjh** [comment]
@hayguen @suamor @cjdelisle I've recently setup automated CI for DUMA using GitLab CI. Everyone (including "guest" users and anyone not logged in) should be able view the CI output at the [Gridfinity GitLab DUMA project page](https://gitlab.gridfinity.com/jeff/duma) as the CI output contains no sensitive data. However, you might need to sign-up for an account on this GitLab instance for more complete access. 

I plan to add additional build variants, but, currently, the macOS build (which is using macOS 11.1 [Big Sur] using Xcode 12.3/Clang on x86_64) is currently compiling successfully, but is not passing the tests. I've not looked into this yet, but I should warn that I have very little experience with using DUMA on OS X and macOS development specifics in general, so if any tips would be appreciated.

**Comment by johnsonjh** [comment]
https://gitlab.gridfinity.com/jeff/duma/-/jobs/499 is a direct link to a failed build job.  

I've attached the build log here as well: [duma_macos_11_gl-runner-build_fail_901741251.log](https://github.com/johnsonjh/duma/files/5720490/duma_macos_11_gl-runner-build_fail_901741251.log) in case that particular job output expires before being viewed (as well to keep a record here at GitHub as well.)

**Comment by johnsonjh** [comment]
On macOS:

DUMA Aborting: 
free(7ff91bc04110): address not from DUMA or already freed. 
Illegal instruction: 4 
Error 132

This seems to be caused by:
1. https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation
2. https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-dyld-environment-variables

I've not yet determined the most proper workaround, but the problem isn't DUMA.

**Comment by johnsonjh** [comment]
Recently got an Apple developer account, when I have time, I'll see if code-signing/notarization is necessary/helpful here.

**Comment by johnsonjh** [comment]
I still intend to address this "properly".

Does anyone have access to an M1 machine they can "loan" to me via SSH?

**Comment by johnsonjh** [comment]
Latest Docker is giving me issues with my setup as well - Right now builds are only automatically tested on Linux, but this will change.

**Comment by johnsonjh** [comment]
Still need volunteers for Apple Silicon dev

**Comment by cjdelisle** [comment]
I can, just make it a simple process and tell me what I have to do

**Comment by johnsonjh** [comment]
@cjdelisle Good to talk to you Caleb - I'll put something fully automated together in the next day or so and let you know.

**Comment by johnsonjh** [comment]
@cjdelisle 

with checkout of current master on M1, output of `gmake && gmake test && gmake installcheck` should be sufficient.

thanks!

**Comment by hayguen** [comment]
@cjdelisle would be great to also check cmake ..

**Comment by cjdelisle** [comment]
* make -> works
* make check -> works
* sudo make install -> unable to place files because of OSX weird permissions, try /usr/local or /opt/something

```
user@armee duma % sudo make install
Password:
Sorry, try again.
Password:
using settings for OS=darwin
using default prefix [/usr]
using default srcdir [.]
using default exec_prefix [/usr]
./make_git_source_version.sh
cc -g -O0 -c duma.c -o duma.o
rm -f libduma.a
ar crv libduma.a dumapp.o duma.o sem_inc.o print.o
a - dumapp.o
a - duma.o
a - sem_inc.o
a - print.o
ranlib libduma.a
cc -g -O0 -fPIC -DPIC -DDUMA_SO_LIBRARY -c duma.c -o duma_so.o
c++ -g -dynamiclib -Wl -o libduma.dylib dumapp_so.o duma_so.o sem_inc_so.o print_so.o -lpthread -lc
c++ -g -dynamiclib -o libduma.dylib dumapp_so.o duma_so.o sem_inc_so.o print_so.o -lpthread -lc
mkdir -p /usr/share/doc/duma
mkdir: cannot create directory ‘/usr/share/doc/duma’: Operation not permitted
make: [install] Error 1 (ignored)
install -m 644 README.md /usr/share/doc/duma
install: cannot create regular file '/usr/share/doc/duma': Operation not permitted
make: *** [install] Error 1
user@armee duma % 
```

* cmake --> works (few warnings)
* make (cmake) --> works
* make test (cmake) --> all pass
* sudo make install (cmake) --> works, uses /usr/local/ and no perm issues

A few warnings during cmake configure you may wish to note:

```
user@armee duma % cd build 
user@armee build % cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.                                                                                              
                                                                                                                                                                                                            
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at confdir/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/wrk/play/duma/build
Scanning dependencies of target createconf
[ 50%] Building C object confdir/CMakeFiles/createconf.dir/__/createconf.c.o
/Users/user/wrk/play/duma/createconf.c:156:19: warning: cast to smaller integer type 'int_fast32_t' (aka 'int') from 'char *' [-Wpointer-to-int-cast]
      TYPE addr = (TYPE)(buffer) + offset;
                  ^~~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:158:11: warning: cast to 'unsigned char *' from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((unsigned char *)addr) = 0;
          ^~~~~~~~~~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:159:11: warning: cast to 'unsigned short *' from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((unsigned short int *)addr) = 0;
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:160:11: warning: cast to 'unsigned int *' from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((unsigned int *)addr) = 0;
          ^~~~~~~~~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:161:11: warning: cast to 'unsigned long *' from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((unsigned long int *)addr) = 0L;
          ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:162:11: warning: cast to 'float *' from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((float *)addr) = 0.0F;
          ^~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:163:11: warning: cast to 'double *' from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((double *)addr) = 0.0;
          ^~~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:164:11: warning: cast to 'long double *' from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((long double *)addr) = 0.0;
          ^~~~~~~~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:166:11: warning: cast to 'int_fast32_t *' (aka 'int *') from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((int_fast32_t *)addr) = 0;
          ^~~~~~~~~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:167:11: warning: cast to 'int_fast64_t *' (aka 'long long *') from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((int_fast64_t *)addr) = 0;
          ^~~~~~~~~~~~~~~~~~~~
/Users/user/wrk/play/duma/createconf.c:173:11: warning: cast to 'unsigned long long *' from smaller integer type 'int_fast32_t' (aka 'int') [-Wint-to-pointer-cast]
        *((unsigned long long int *)addr) = 0L;
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11 warnings generated.
[100%] Linking C executable createconf
[100%] Built target createconf
-- target link pthread to DUMA_SHARED
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   DUMA_SHARED

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/user/wrk/play/duma/build
user@armee build % 
```

Thanks

**Comment by johnsonjh** [comment]
@cjdelisle 

Thank you very much, that helps a lot.

**Comment by johnsonjh** [comment]
Now, will verify x64 is OK and if so close.

also will address the gnumake paths on OS X - can do this in my VM

**Comment by hayguen** [comment]
> * cmake --> works (few warnings)
> * make (cmake) --> works
> * make test (cmake) --> all pass
> * sudo make install (cmake) --> works, uses /usr/local/ and no perm issues
> 
> A few warnings during cmake configure you may wish to note:

@cjdelisle thank you very much. that looks quite good :-)

the cmake warnings need some work.
think, the compiler warnings are OK, cause they are from the configuration step. sure, it would be better, if we could remove them .. but not sure if possible.

**Comment by johnsonjh** [comment]
Building seems to work on x64 fine as well - I'll update default paths for GNUmake installation and document overriding them, probably will be merging INSTALL - then I'll close this issue

**Comment by johnsonjh** [comment]
will merge
