### ISSUE TITLE
move detours and kduma into attic subfolder?

### ISSUE THREAD

**Issue by hayguen** [johnsonjh/duma#45]
i don't know if anyone had a look or tried detours or kduma for many many years?:
thus, i would suggest to move the detours folder and kduma into some "attic" subfolder

**Comment by johnsonjh** [comment]
Fixed in 67dd494a2cc200084d570323b066e77599711021

(Store ... at least temporarily)

**Comment by johnsonjh** [comment]
Also rebased automated changed
