### ISSUE TITLE
Verify and possibly overhaul INSTALL

### ISSUE THREAD

**Issue by johnsonjh** [johnsonjh/duma#63]
Ensure INSTALL details are accurate and reflect reality.

**Comment by johnsonjh** [comment]
Probably makes sense to merge `INSTALL` into `README.md` as a section near the top, before ***Usage*** and document building with both CMake and GNUmake

**Comment by hayguen** [comment]
At least have a link to it

**Comment by johnsonjh** [comment]
I'll close this and handle as part of #3
