### ISSUE TITLE
Create PowerShell version of make_git_source_version.sh

### ISSUE THREAD

**Issue by johnsonjh** [johnsonjh/duma#66]
Create PowerShell version of `make_git_source_version.sh` for native Windows builds from git checkout.

**Comment by johnsonjh** [comment]
.... my god that script is complex, what was I thinking? 😨

**Comment by hayguen** [comment]
someone else surely already has a solution for windows.
(i'm now away for several hours from now. good luck!)

**Comment by johnsonjh** [comment]
One would hope - it's low-low-priority - Windows Git-Bash is sufficient, but not quite "native"

**Comment by johnsonjh** [comment]
>(i'm now away for several hours from now. good luck!)
Thanks - I'll be looking to complete the comparison and HTML today.

**Comment by johnsonjh** [comment]
Will test a more native VS solution, but likely won't be rewriting this for native builds - closing for now (won't add extra complexity with a PS version)
