### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by johnsonjh** [johnsonjh/duma#85]
- use configuration file, which is read directly with system calls as replacement for the environment switches which use calls to the C library. this is to avoid hangs in the C library's getenv() function.
   -  --> outdated: now using `char **environ variable instead getenv()`

relevant?

**Comment by hayguen** [comment]
> relevant?

don't think so - as there's no known bug (real problem) with this

**Comment by johnsonjh** [comment]
Closing for now, will open a new issue if needed
