### ISSUE TITLE
Recover duma_iue.tgz?

### ISSUE THREAD

**Issue by johnsonjh** [johnsonjh/duma#88]
* http://tutorial.gsse.at/uploads/media/duma_iue.tgz

     * Not on archive.org wayback, unfortunately

**Comment by johnsonjh** [comment]
@hayguen 

do you have a copy of this file or know what the contents were?

I spent some time (less than an hour, but not sure where else to look) and couldn't find it.

**Comment by hayguen** [comment]
i have no copy .. and no idea about the contents

**Comment by johnsonjh** [comment]
Thanks - I'll close for now then.
